language: node_js
node_js: node

os:
  - osx

env:
  global:
    - ELM_VERSION=0.19.0-bugfix2
    - ELM_TEST_VERSION=^0.19.0-beta5

install:
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST_VERSION

script:
  - make all test
